engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - scss
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: .eslintrc
  scss-lint:
    enabled: true
ratings:
  paths:
    - "js/**.js"
    - "scss/**.scss"
  exclude_paths:
    - dist/
