engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - scss
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc.json
  scss-lint:
    enabled: true
ratings:
  paths:
    - "js/**.js"
    - "scss/**.scss"
  exclude_paths:
    - dist/
