engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - scss
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc.json
  markdownlint:
    enabled: true
ratings:
  paths:
    - "js/**.js"
    - "**.md"
  exclude_paths:
    - dist/
    - "!LICENSE.md"
